// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mddwmfdtfqwxculoejcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kZHdtZmR0ZnF3eGN1bG9lamNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzE1ODcsImV4cCI6MjA3MDAwNzU4N30._IriqB-NQ7F0jC8Ujw_LhSIBAsW-cCX1LDWLbTJtdIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});